name: BHome
version: 1.5
description: Player home commands
author: RedstoneFiend
website: https://github.com/RedstoneFiend/BHome

main: io.github.redstonefiend.bhome.Main
database: false

commands:
    bhome:
        description: Boomerang Home administrative commands.
        usage: /<command> [ver[sion] | reload | max [number] | show <player> [home] | tp <player> [home]]
        permission: bhome.admin
    sethome:
        description: Set a home.
        usage: /<command> [name]
        permission: bhome.home
    delhome:
        description: Delete a home.
        usage: /<command> [name]
        permission: bhome.home
    home:
        description: List homes or teleport to a home if name is specified.
        usage: /<command> [name]
        permission: bhome.home

# Permissions
permissions:
    bhome.*:
        description: Gives access to all BHome commands
        children:
            bhome.bhome: true
            bhome.home: true
    bhome.admin:
        description: Allows access to administrative commands.
        default: op
    bhome.home:
        description: Allows access to home commands.
        default: op
